# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aldd0 <- function(pars, X1, X2, yvec, tau, C, dupid, dcate) {
    .Call(`_egpdgam2_aldd0`, pars, X1, X2, yvec, tau, C, dupid, dcate)
}

aldd12 <- function(pars, X1, X2, yvec, tau, C, dupid, dcate) {
    .Call(`_egpdgam2_aldd12`, pars, X1, X2, yvec, tau, C, dupid, dcate)
}

aldd34 <- function(pars, X1, X2, yvec, tau, C, dupid, dcate) {
    .Call(`_egpdgam2_aldd34`, pars, X1, X2, yvec, tau, C, dupid, dcate)
}

egpdd0 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_egpdgam2_egpdd0`, pars, X1, X2, X3, yvec, dupid, dcate)
}

egpdd12 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_egpdgam2_egpdd12`, pars, X1, X2, X3, yvec, dupid, dcate)
}

egpdcd0 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_egpdgam2_egpdcd0`, pars, X1, X2, X3, yvec, dupid, dcate)
}

egpdcd12 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_egpdgam2_egpdcd12`, pars, X1, X2, X3, yvec, dupid, dcate)
}

exid0 <- function(yvec, zvec, pars, nmax, X, dupid, dcate, link) {
    .Call(`_egpdgam2_exid0`, yvec, zvec, pars, nmax, X, dupid, dcate, link)
}

exid12 <- function(yvec, zvec, pars, nmax, X, dupid, dcate, link) {
    .Call(`_egpdgam2_exid12`, yvec, zvec, pars, nmax, X, dupid, dcate, link)
}

exid34 <- function(yvec, zvec, pars, nmax, X, dupid, dcate, link) {
    .Call(`_egpdgam2_exid34`, yvec, zvec, pars, nmax, X, dupid, dcate, link)
}

#' Running maximum
#' 
#' Running \eqn{n}-value maximum and data frame with variable swapped for running maximum
#'
#' @param y a vector
#' @param n an integer giving the number of observations to calculate running maxmimum over; defaults to 2
#'
#' @return \code{runmax} returns a vector of the same dimension as \code{y}
#'
#' @examples
#' runmax(runif(10), 5)
#'
#' @name runmax
#'
#' @export
runmax <- function(y, n) {
    .Call(`_egpdgam2_runmax`, y, n)
}

expd0 <- function(pars, X1, yvec, dupid, dcate) {
    .Call(`_egpdgam2_expd0`, pars, X1, yvec, dupid, dcate)
}

expd12 <- function(pars, X1, yvec, dupid, dcate) {
    .Call(`_egpdgam2_expd12`, pars, X1, yvec, dupid, dcate)
}

expd34 <- function(pars, X1, yvec, dupid, dcate) {
    .Call(`_egpdgam2_expd34`, pars, X1, yvec, dupid, dcate)
}

armapinv <- function(x, tol) {
    .Call(`_egpdgam2_armapinv`, x, tol)
}

armaginv <- function(x, tol) {
    .Call(`_egpdgam2_armaginv`, x, tol)
}

gaussd0 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_egpdgam2_gaussd0`, pars, X1, X2, yvec, dupid, dcate)
}

gaussd12 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_egpdgam2_gaussd12`, pars, X1, X2, yvec, dupid, dcate)
}

gaussd34 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_egpdgam2_gaussd34`, pars, X1, X2, yvec, dupid, dcate)
}

gevd0 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_egpdgam2_gevd0`, pars, X1, X2, X3, yvec, dupid, dcate)
}

gevd12 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_egpdgam2_gevd12`, pars, X1, X2, X3, yvec, dupid, dcate)
}

gevd34 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_egpdgam2_gevd34`, pars, X1, X2, X3, yvec, dupid, dcate)
}

mean_arr <- function(x, n) {
    .Call(`_egpdgam2_mean_arr`, x, n)
}

ragged_mean_vec <- function(x, n) {
    .Call(`_egpdgam2_ragged_mean_vec`, x, n)
}

ragged_mean_mat <- function(x, n) {
    .Call(`_egpdgam2_ragged_mean_mat`, x, n)
}

ldgev <- function(yvec, muvec, lpsivec, xivec) {
    .Call(`_egpdgam2_ldgev`, yvec, muvec, lpsivec, xivec)
}

ldgev12 <- function(yvec, muvec, lpsivec, xivec) {
    .Call(`_egpdgam2_ldgev12`, yvec, muvec, lpsivec, xivec)
}

ldgevagg <- function(yvec, muvec, lpsivec, xivec, thetavec) {
    .Call(`_egpdgam2_ldgevagg`, yvec, muvec, lpsivec, xivec, thetavec)
}

ldgevagg12 <- function(yvec, muvec, lpsivec, xivec, thetavec) {
    .Call(`_egpdgam2_ldgevagg12`, yvec, muvec, lpsivec, xivec, thetavec)
}

gevcd0 <- function(pars, X1, X2, X3, ymat, dupid, dcate) {
    .Call(`_egpdgam2_gevcd0`, pars, X1, X2, X3, ymat, dupid, dcate)
}

gevcd12 <- function(pars, X1, X2, X3, ymat, dupid, dcate) {
    .Call(`_egpdgam2_gevcd12`, pars, X1, X2, X3, ymat, dupid, dcate)
}

gevcd34 <- function(pars, X1, X2, X3, ymat, dupid, dcate) {
    .Call(`_egpdgam2_gevcd34`, pars, X1, X2, X3, ymat, dupid, dcate)
}

gpdd0 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_egpdgam2_gpdd0`, pars, X1, X2, yvec, dupid, dcate)
}

gpdd12 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_egpdgam2_gpdd12`, pars, X1, X2, yvec, dupid, dcate)
}

gpdd34 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_egpdgam2_gpdd34`, pars, X1, X2, yvec, dupid, dcate)
}

gpdcd0 <- function(pars, X1, X2, ymat, dupid, dcate) {
    .Call(`_egpdgam2_gpdcd0`, pars, X1, X2, ymat, dupid, dcate)
}

gpdcd12 <- function(pars, X1, X2, ymat, dupid, dcate) {
    .Call(`_egpdgam2_gpdcd12`, pars, X1, X2, ymat, dupid, dcate)
}

gpdcd34 <- function(pars, X1, X2, ymat, dupid, dcate) {
    .Call(`_egpdgam2_gpdcd34`, pars, X1, X2, ymat, dupid, dcate)
}

.gH1 <- function(gh, X1, dupid, dcate, sand, deriv) {
    .Call(`_egpdgam2_gH1`, gh, X1, dupid, dcate, sand, deriv)
}

.gH2 <- function(gh, X1, X2, dupid, dcate, sand, deriv) {
    .Call(`_egpdgam2_gH2`, gh, X1, X2, dupid, dcate, sand, deriv)
}

.gH3 <- function(gh, X1, X2, X3, dupid, dcate, sand, deriv) {
    .Call(`_egpdgam2_gH3`, gh, X1, X2, X3, dupid, dcate, sand, deriv)
}

.gH4 <- function(gh, X1, X2, X3, X4, dupid, dcate, sand, deriv) {
    .Call(`_egpdgam2_gH4`, gh, X1, X2, X3, X4, dupid, dcate, sand, deriv)
}

pp1d0 <- function(pars, X1, X2, X3, yvec, wvec) {
    .Call(`_egpdgam2_pp1d0`, pars, X1, X2, X3, yvec, wvec)
}

pp1d12 <- function(pars, X1, X2, X3, yvec, wvec) {
    .Call(`_egpdgam2_pp1d12`, pars, X1, X2, X3, yvec, wvec)
}

pp1d34 <- function(pars, X1, X2, X3, yvec, wvec) {
    .Call(`_egpdgam2_pp1d34`, pars, X1, X2, X3, yvec, wvec)
}

pp2d0 <- function(pars, X1, X2, X3, yvec, wvec) {
    .Call(`_egpdgam2_pp2d0`, pars, X1, X2, X3, yvec, wvec)
}

pp2d12 <- function(pars, X1, X2, X3, yvec) {
    .Call(`_egpdgam2_pp2d12`, pars, X1, X2, X3, yvec)
}

pp2d34 <- function(pars, X1, X2, X3, yvec) {
    .Call(`_egpdgam2_pp2d34`, pars, X1, X2, X3, yvec)
}

ppcd0 <- function(pars, X1, X2, X3, yvec, wvec) {
    .Call(`_egpdgam2_ppcd0`, pars, X1, X2, X3, yvec, wvec)
}

ppcd12 <- function(pars, X1, X2, X3, yvec) {
    .Call(`_egpdgam2_ppcd12`, pars, X1, X2, X3, yvec)
}

ppcd34 <- function(pars, X1, X2, X3, yvec) {
    .Call(`_egpdgam2_ppcd34`, pars, X1, X2, X3, yvec)
}

ppexi1d0 <- function(pars, X1, X2, X3, X4, yvec, wvec) {
    .Call(`_egpdgam2_ppexi1d0`, pars, X1, X2, X3, X4, yvec, wvec)
}

ppexi1d12 <- function(pars, X1, X2, X3, X4, yvec, wvec) {
    .Call(`_egpdgam2_ppexi1d12`, pars, X1, X2, X3, X4, yvec, wvec)
}

ppexi1d34 <- function(pars, X1, X2, X3, X4, yvec, wvec) {
    .Call(`_egpdgam2_ppexi1d34`, pars, X1, X2, X3, X4, yvec, wvec)
}

ppexi2d0 <- function(pars, X1, X2, X3, X4, yvec, wvec) {
    .Call(`_egpdgam2_ppexi2d0`, pars, X1, X2, X3, X4, yvec, wvec)
}

ppexi2d12 <- function(pars, X1, X2, X3, X4, yvec, wvec) {
    .Call(`_egpdgam2_ppexi2d12`, pars, X1, X2, X3, X4, yvec, wvec)
}

ppexi2d34 <- function(pars, X1, X2, X3, X4, yvec, wvec) {
    .Call(`_egpdgam2_ppexi2d34`, pars, X1, X2, X3, X4, yvec, wvec)
}

rcpp_hello_world <- function() {
    .Call(`_egpdgam2_rcpp_hello_world`)
}

weibd0 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_egpdgam2_weibd0`, pars, X1, X2, yvec, dupid, dcate)
}

weibd12 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_egpdgam2_weibd12`, pars, X1, X2, yvec, dupid, dcate)
}

weibd34 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_egpdgam2_weibd34`, pars, X1, X2, yvec, dupid, dcate)
}

